import { noteFrequencies } from "../config.js";
import { getAudioContext, musicEnabled } from "./audio.js";

export const continuousEngine={
    pianoOsc:null,pianoGain:null,pianoMasterGain:null,violinOsc:null,violinGain:null,violinFilter:null,violinMasterGain:null,bassOsc:null,bassGain:null,bassFilter:null,bassMasterGain:null,
    activeType:'piano',currentFreq:523.25,isRunning:false,
    start(){if(this.isRunning||!getAudioContext()||!musicEnabled)return;this.isRunning=true;this.activeType='piano';this.createPiano();},
    createPiano(){const a=getAudioContext(),now=a.currentTime;this.pianoMasterGain=a.createGain();this.pianoMasterGain.gain.value=0;this.pianoMasterGain.connect(a.destination);const ps=[{freq:1,gain:.3},{freq:2,gain:.15},{freq:3,gain:.08}];this.pianoOsc=[];this.pianoGain=[];ps.forEach(p=>{const o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=this.currentFreq*p.freq;g.gain.value=p.gain;o.connect(g).connect(this.pianoMasterGain);o.start(now);this.pianoOsc.push(o);this.pianoGain.push(g);});},
    createViolin(){const a=getAudioContext(),now=a.currentTime;this.violinMasterGain=a.createGain();this.violinMasterGain.gain.value=0;this.violinMasterGain.connect(a.destination);this.violinOsc=a.createOscillator();this.violinFilter=a.createBiquadFilter();this.violinGain=a.createGain();this.violinOsc.type='sawtooth';this.violinOsc.frequency.value=this.currentFreq;this.violinFilter.type='lowpass';this.violinFilter.frequency.value=1200;this.violinFilter.Q.value=.5;this.violinGain.gain.value=.25;this.violinOsc.connect(this.violinFilter);this.violinFilter.connect(this.violinGain);this.violinGain.connect(this.violinMasterGain);this.violinOsc.start(now);},
    createBass(){const a=getAudioContext(),now=a.currentTime;this.bassMasterGain=a.createGain();this.bassMasterGain.gain.value=0;this.bassMasterGain.connect(a.destination);this.bassOsc=a.createOscillator();this.bassFilter=a.createBiquadFilter();this.bassGain=a.createGain();this.bassOsc.type='sawtooth';this.bassOsc.frequency.value=this.currentFreq/2;this.bassFilter.type='lowpass';this.bassFilter.frequency.value=500;this.bassFilter.Q.value=.8;this.bassGain.gain.value=.3;this.bassOsc.connect(this.bassFilter).connect(this.bassGain).connect(this.bassMasterGain);this.bassOsc.start(now);},
    switchInstrument(type){if(!this.isRunning||!getAudioContext()||!musicEnabled)return;const a=getAudioContext(),now=a.currentTime,oldType=this.activeType;if(oldType===type)return;if(type==='piano'){this.createPiano();this.pianoMasterGain.gain.setValueAtTime(0,now);this.pianoMasterGain.gain.linearRampToValueAtTime(.25,now+.2);}else if(type==='violin'){this.createViolin();this.violinMasterGain.gain.setValueAtTime(0,now);this.violinMasterGain.gain.linearRampToValueAtTime(.25,now+.2);}else if(type==='bass'){this.createBass();this.bassMasterGain.gain.setValueAtTime(0,now);this.bassMasterGain.gain.linearRampToValueAtTime(.3,now+.2);}
        if(oldType==='piano'&&this.pianoMasterGain){this.pianoMasterGain.gain.setValueAtTime(this.pianoMasterGain.gain.value,now);this.pianoMasterGain.gain.linearRampToValueAtTime(0,now+.3);setTimeout(()=>{if(this.pianoOsc){this.pianoOsc.forEach(o=>{try{o.stop()}catch(e){}});this.pianoOsc=null;this.pianoMasterGain.disconnect();this.pianoMasterGain=null;}},350);}
        else if(oldType==='violin'&&this.violinOsc){this.violinMasterGain.gain.setValueAtTime(this.violinMasterGain.gain.value,now);this.violinMasterGain.gain.linearRampToValueAtTime(0,now+.3);setTimeout(()=>{this.violinOsc.stop();this.violinOsc=null;this.violinMasterGain.disconnect();this.violinMasterGain=null;},350);}
        else if(oldType==='bass'&&this.bassOsc){this.bassMasterGain.gain.setValueAtTime(this.bassMasterGain.gain.value,now);this.bassMasterGain.gain.linearRampToValueAtTime(0,now+.3);setTimeout(()=>{this.bassOsc.stop();this.bassOsc=null;this.bassMasterGain.disconnect();this.bassMasterGain=null;},350);}
        this.activeType=type;},
    glideToFreq(newFreq,duration=.08){if(!this.isRunning||!getAudioContext()||!musicEnabled)return;const a=getAudioContext(),now=a.currentTime;this.currentFreq=newFreq;if(this.activeType==='piano'&&this.pianoOsc)this.pianoOsc.forEach((o,i)=>{const partial=[1,2,3][i];o.frequency.cancelScheduledValues(now);o.frequency.setValueAtTime(o.frequency.value,now);o.frequency.linearRampToValueAtTime(newFreq*partial,now+duration);});else if(this.activeType==='violin'&&this.violinOsc){this.violinOsc.frequency.cancelScheduledValues(now);this.violinOsc.frequency.setValueAtTime(this.violinOsc.frequency.value,now);this.violinOsc.frequency.linearRampToValueAtTime(newFreq,now+duration);}else if(this.activeType==='bass'&&this.bassOsc){this.bassOsc.frequency.cancelScheduledValues(now);this.bassOsc.frequency.setValueAtTime(this.bassOsc.frequency.value,now);this.bassOsc.frequency.linearRampToValueAtTime(newFreq/2,now+duration);}},
    noteAttack(volume=.25){if(!this.isRunning||!getAudioContext()||!musicEnabled)return;const a=getAudioContext(),now=a.currentTime,attackTime=.02,decayTime=1;if(this.activeType==='piano'&&this.pianoMasterGain){this.pianoMasterGain.gain.cancelScheduledValues(now);this.pianoMasterGain.gain.setValueAtTime(0,now);this.pianoMasterGain.gain.linearRampToValueAtTime(volume,now+attackTime);this.pianoMasterGain.gain.exponentialRampToValueAtTime(.001,now+attackTime+decayTime);}else if(this.activeType==='violin'&&this.violinMasterGain){this.violinMasterGain.gain.cancelScheduledValues(now);this.violinMasterGain.gain.setValueAtTime(0,now);this.violinMasterGain.gain.linearRampToValueAtTime(volume,now+.05);this.violinMasterGain.gain.exponentialRampToValueAtTime(.001,now+.05+decayTime);}else if(this.activeType==='bass'&&this.bassMasterGain){this.bassMasterGain.gain.cancelScheduledValues(now);this.bassMasterGain.gain.setValueAtTime(0,now);this.bassMasterGain.gain.linearRampToValueAtTime(.4,now+.01);this.bassMasterGain.gain.exponentialRampToValueAtTime(.001,now+.01+decayTime);}},
    stop(){this.isRunning=false;const a=getAudioContext(),now=a?a.currentTime:0;if(this.pianoMasterGain){this.pianoMasterGain.gain.setValueAtTime(0,now);this.pianoOsc.forEach(o=>{try{o.stop(now+.1)}catch(e){}});this.pianoOsc=null;this.pianoMasterGain.disconnect();this.pianoMasterGain=null;}if(this.violinMasterGain){this.violinMasterGain.gain.setValueAtTime(0,now);this.violinOsc.stop(now+.1);this.violinOsc=null;this.violinMasterGain.disconnect();this.violinMasterGain=null;}if(this.bassMasterGain){this.bassMasterGain.gain.setValueAtTime(0,now);this.bassOsc.stop(now+.1);this.bassOsc=null;this.bassMasterGain.disconnect();this.bassMasterGain=null;}}
};
export function playSmoothNote(index,type){const a=getAudioContext();if(!a||!musicEnabled)return;continuousEngine.start();continuousEngine.switchInstrument(type);continuousEngine.glideToFreq(noteFrequencies[index],.06);continuousEngine.noteAttack(.25);}
