import {ctx,W,H,rand} from "./core.js";
import {state} from "./state.js";
import {clouds} from "./game/clouds.js";
import {particles} from "./game/particles.js";
import {lightning} from "./game/lightning.js";
import {weatherEnabled,weatherParticles} from "./game/weather.js";
import {rainbowColors} from "./config.js";
const stars=[];for(let i=0;i<100;i++)stars.push({x:Math.random(),y:Math.random()*.7,r:rand(.5,1.8),twinkle:rand(0,Math.PI*2)});
const darkClouds=[];for(let i=0;i<7;i++)darkClouds.push({x:rand(-100,W),y:rand(20,H*.4),scale:rand(.7,1.5),speed:rand(5,18)});
export function updateDarkClouds(dt){if(state.gameState==="success")return;for(const c of darkClouds){c.x+=c.speed*dt;if(c.x>W+200)c.x=-250;}}
function drawSky(){let top,bottom;if(state.gameState==="success"){top="#5dbbff";bottom="#e9faff";}else{top="#050b19";bottom="#1d2b48";}const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,top);g.addColorStop(1,bottom);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}
function drawStars(){if(state.gameState==="success")return;for(const s of stars){ctx.globalAlpha=.35+Math.sin(state.time*2+s.twinkle)*.25;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(s.x*W,s.y*H,s.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
function drawDarkClouds(){if(state.gameState==="success")return;ctx.textAlign="center";ctx.textBaseline="middle";for(const c of darkClouds){ctx.font=`${100*c.scale}px "Segoe UI Emoji","Apple Color Emoji","Noto Color Emoji",sans-serif`;ctx.fillText("🌧️",c.x,c.y);}}
function drawWeather(){if(!weatherEnabled)return;ctx.textAlign="center";ctx.textBaseline="middle";for(const p of weatherParticles){if(p.type==="rain"){ctx.strokeStyle="rgba(160,200,255,0.4)";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+p.driftX*.05,p.y+p.length);ctx.stroke();}else{ctx.font=`${p.length*1.5}px "Segoe UI Emoji","Apple Color Emoji","Noto Color Emoji",sans-serif`;ctx.fillText("❄️",p.x,p.y);}}}
function drawCloud(c){if(c.alpha<=.01)return;const y=c.y+state.worldY+Math.sin(state.time*2+c.bob)*4;ctx.save();ctx.globalAlpha=c.alpha;ctx.translate(c.x,y);ctx.rotate(c.rotation);ctx.font=`${Math.min(c.width,c.height*3)}px "Segoe UI Emoji","Apple Color Emoji","Noto Color Emoji",sans-serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("☁️",0,0);ctx.restore();}
function drawParticles(){for(const p of particles){const a=p.life/p.maxLife;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation);ctx.globalAlpha=a;ctx.fillStyle="#fff";ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size);ctx.restore();}ctx.globalAlpha=1;}
function drawGround(){const sy=state.groundY+state.worldY;if(sy>H+100||sy<-100)return;const g=ctx.createLinearGradient(0,sy,0,sy+100);g.addColorStop(0,"#fff");g.addColorStop(1,"#cfd8e8");ctx.fillStyle=g;ctx.fillRect(0,sy,W,H-sy);}
function drawPlayer(){ctx.save();ctx.translate(state.player.x,state.player.y);ctx.rotate(state.player.rotating?state.player.rotation:state.player.rotation*.2);ctx.font=`${state.player.radius*2}px "Segoe UI Emoji","Apple Color Emoji","Noto Color Emoji",sans-serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("🦄",0,0);ctx.restore();}
function drawLightning(){if(lightning.warning){const pulse=Math.sin(lightning.timer*12)*.5+.5;ctx.fillStyle=`rgba(10,10,20,${.55+pulse*.2})`;ctx.beginPath();ctx.ellipse(lightning.x,-10,100,55,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=`rgba(180,190,255,${.15+pulse*.4})`;ctx.setLineDash([8,10]);ctx.beginPath();ctx.moveTo(lightning.x,20);ctx.lineTo(lightning.x,state.player.y);ctx.stroke();ctx.setLineDash([]);}if(lightning.active){ctx.strokeStyle="#fff";ctx.lineWidth=5;ctx.shadowColor="#8fa8ff";ctx.shadowBlur=30;ctx.beginPath();ctx.moveTo(lightning.x,0);let y=0;for(let i=0;i<7;i++){y+=rand(40,80);ctx.lineTo(lightning.x+rand(-30,30),y);}ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=`rgba(255,255,255,${lightning.flash*.35})`;ctx.fillRect(0,0,W,H);}}
function drawFinalRainbow(){if(state.gameState!=="success")return;const cx=W/2,cy=H+100-state.rainbowAnimation*220,radius=Math.min(W*.42,300)*state.rainbowAnimation;ctx.save();ctx.lineWidth=18;for(let i=0;i<7;i++){ctx.strokeStyle=rainbowColors[i];ctx.beginPath();ctx.arc(cx,cy,radius+i*16,Math.PI,Math.PI*2);ctx.stroke();}ctx.restore();const sunY=H*.18+state.rainbowAnimation*30,sun=ctx.createRadialGradient(W*.78,sunY,5,W*.78,sunY,100);sun.addColorStop(0,"rgba(255,255,210,1)");sun.addColorStop(1,"rgba(255,220,80,0)");ctx.fillStyle=sun;ctx.fillRect(0,0,W,H);ctx.fillStyle="#fff4a0";ctx.beginPath();ctx.arc(W*.78,sunY,42,0,Math.PI*2);ctx.fill();}
function drawBarrage(){if(!state.barrageActive||state.gameState!=="success")return;ctx.save();ctx.font='bold 60px "Segoe UI",sans-serif';ctx.textAlign="center";ctx.textBaseline="middle";ctx.shadowColor="rgba(0,0,0,.7)";ctx.shadowBlur=10;ctx.fillStyle="#fff";ctx.fillText("冲上云霄！",state.barrageX,H*.5);ctx.restore();}
function drawCursorEmoji(){if(state.gameState==="success")return;ctx.font='24px "Segoe UI Emoji","Apple Color Emoji","Noto Color Emoji",sans-serif';ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("🌈",state.input.x,state.input.y);}
export function draw(){drawSky();drawStars();drawDarkClouds();drawWeather();for(const c of clouds)drawCloud(c);drawParticles();drawGround();drawPlayer();drawLightning();drawFinalRainbow();drawBarrage();drawCursorEmoji();}
